version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
    - "sebastian-sz"
  reviewers:
    - "sebastian-sz"
  allow:
  - dependency-name: tensorflow
